#!/bin/sh

PROTECTED_BRANCHES="^\*"

DEFAULT_BRANCH=`git config init.defaultBranch`
if [ -n "$DEFAULT_BRANCH" ]; then
    PROTECTED_BRANCHES="$PROTECTED_BRANCHES|$DEFAULT_BRANCH"
fi

CUSTOM_PROTECTED=`git config brrr.protectedBranches`
if [ -n "$CUSTOM_PROTECTED" ]; then
    PROTECTED_BRANCHES="$PROTECTED_BRANCHES|$CUSTOM_PROTECTED"
fi

git branch --merged | egrep -v "($PROTECTED_BRANCHES)" | xargs git branch -d
